import {
  AlertTriangle,
  Boxes,
  ClipboardCheck,
  ClipboardList,
  Columns3,
  CreditCard,
  FileText,
  FolderTree,
  GitBranch,
  History,
  LayoutDashboard,
  Lightbulb,
  MapPin,
  Package,
  PhoneCall,
  ScrollText,
  TrendingUp,
  UserPlus,
  Receipt,
  ShoppingCart,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";
import { PERMISSIONS, ROUTES } from "../../shared/constants";

export const superAdminNavigation = [
  {
    label: "Dashboard",
    route: ROUTES.SUPER_ADMIN.DASHBOARD,
    icon: LayoutDashboard,
  },
  {
    label: "Employees",
    route: ROUTES.SUPER_ADMIN.EMPLOYEES,
    icon: Users,
    permission: PERMISSIONS.EMPLOYEES_READ,
  },
  {
    label: "Pending Approvals",
    route: ROUTES.SUPER_ADMIN.EMPLOYEE_PENDING,
    icon: ClipboardCheck,
    permission: PERMISSIONS.EMPLOYEES_APPROVE,
  },
  {
    label: "Hierarchy",
    route: ROUTES.SUPER_ADMIN.EMPLOYEE_HIERARCHY,
    icon: GitBranch,
    permission: PERMISSIONS.EMPLOYEES_READ,
  },
  {
    label: "Regions",
    route: ROUTES.SUPER_ADMIN.REGIONS,
    icon: MapPin,
    permission: PERMISSIONS.REGION_READ,
  },
  {
    label: "Districts",
    route: ROUTES.SUPER_ADMIN.DISTRICTS,
    icon: GitBranch,
    permission: PERMISSIONS.DISTRICT_READ,
  },
  {
    label: "Hiring Requests",
    route: ROUTES.SUPER_ADMIN.HIRING,
    icon: UserPlus,
    permission: PERMISSIONS.HIRING_READ,
  },
  {
    label: "Promotion Approvals",
    route: ROUTES.SUPER_ADMIN.PROMOTION_APPROVALS,
    icon: TrendingUp,
    permission: PERMISSIONS.PROMOTION_READ,
  },
  {
    label: "Salary Proposals",
    route: ROUTES.SUPER_ADMIN.SALARY_PROPOSAL_APPROVALS,
    icon: Wallet,
    permission: PERMISSIONS.SALARY_PROPOSAL_READ,
  },
  {
    label: "Categories",
    route: ROUTES.SUPER_ADMIN.CATEGORIES,
    icon: FolderTree,
    permission: PERMISSIONS.CATEGORIES_READ,
  },
  {
    label: "Products",
    route: ROUTES.SUPER_ADMIN.PRODUCTS,
    icon: Package,
    permission: PERMISSIONS.PRODUCTS_READ,
  },
  {
    label: "Inventory",
    route: ROUTES.SUPER_ADMIN.INVENTORY,
    icon: Warehouse,
    permission: PERMISSIONS.INVENTORY_READ,
  },
  {
    label: "CRM",
    route: ROUTES.SUPER_ADMIN.CRM,
    icon: Columns3,
    permission: PERMISSIONS.LEADS_READ,
  },
  {
    label: "Leads",
    route: ROUTES.SUPER_ADMIN.LEADS,
    icon: PhoneCall,
    permission: PERMISSIONS.LEADS_READ,
  },
  {
    label: "Follow-Ups",
    route: ROUTES.SUPER_ADMIN.FOLLOW_UPS,
    icon: ClipboardCheck,
    permission: PERMISSIONS.LEADS_READ,
  },
  {
    label: "Quotations",
    route: ROUTES.SUPER_ADMIN.QUOTATIONS,
    icon: FileText,
    permission: PERMISSIONS.QUOTATIONS_READ,
  },
  {
    label: "DSRs",
    route: ROUTES.SUPER_ADMIN.DSR,
    icon: ClipboardList,
    permission: PERMISSIONS.DSR_READ_ALL,
  },
  {
    label: "Product Recommendations",
    route: ROUTES.SUPER_ADMIN.PRODUCT_RECOMMENDATIONS,
    icon: Lightbulb,
    permission: PERMISSIONS.PRODUCTS_READ,
  },
  {
    label: "Customers",
    route: ROUTES.SUPER_ADMIN.CUSTOMERS,
    icon: Users,
    permission: PERMISSIONS.CUSTOMERS_READ,
  },
  {
    label: "Orders",
    route: ROUTES.SUPER_ADMIN.ORDERS,
    icon: ShoppingCart,
    permission: PERMISSIONS.ORDERS_READ,
  },
  {
    label: "Invoices",
    route: ROUTES.SUPER_ADMIN.INVOICES,
    icon: Receipt,
    permission: PERMISSIONS.INVOICES_READ,
  },
  // Flat sibling of "Invoices", not nested under it — Prompt 57 marks
  // nesting as optional, and this app's nav renderer has no support for a
  // `children` structure at all (verified in InternalAppLayout.jsx); this
  // mirrors the exact "Inventory" / "Low Stock" / "Out Of Stock" /
  // "Transactions" flat-sibling pattern already used a few entries below.
  {
    label: "Outstanding",
    route: ROUTES.SUPER_ADMIN.INVOICE_OUTSTANDING,
    icon: AlertTriangle,
    permission: PERMISSIONS.INVOICES_READ,
  },
  {
    label: "Payments",
    route: ROUTES.SUPER_ADMIN.PAYMENTS,
    icon: CreditCard,
    permission: PERMISSIONS.PAYMENTS_READ,
  },
  {
    label: "Low Stock",
    route: ROUTES.SUPER_ADMIN.INVENTORY_LOW_STOCK,
    icon: AlertTriangle,
    permission: PERMISSIONS.INVENTORY_READ,
  },
  {
    label: "Out Of Stock",
    route: ROUTES.SUPER_ADMIN.INVENTORY_OUT_OF_STOCK,
    icon: Boxes,
    permission: PERMISSIONS.INVENTORY_READ,
  },
  {
    label: "Transactions",
    route: ROUTES.SUPER_ADMIN.INVENTORY_TRANSACTIONS,
    icon: History,
    permission: PERMISSIONS.INVENTORY_TRANSACTIONS_READ,
  },
  {
    label: "Audit Log",
    route: ROUTES.SUPER_ADMIN.AUDIT_LOG,
    icon: ScrollText,
    permission: PERMISSIONS.AUDIT_READ,
  },
];
