import { env } from "../config";

export const API_CONFIG = Object.freeze({
  baseURL: env.apiBaseUrl,
  timeout: 15000,
  withCredentials: true,
});

export const API_ENDPOINTS = Object.freeze({
  HEALTH: "/health",
  AUTH: {
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  EMPLOYEES: {
    BASE: "/employees",
    REGISTER: "/employees/register",
    ME: "/employees/me",
    MY_TEAM: "/employees/my-team",
    PENDING: "/employees/pending",
    HIERARCHY: "/employees/hierarchy",
    SUMMARY: "/employees/summary",
    DETAIL: (employeeId) => `/employees/${employeeId}`,
    MANAGER: (employeeId) => `/employees/${employeeId}/manager`,
    REPORTS: (employeeId) => `/employees/${employeeId}/reports`,
    DEACTIVATE: (employeeId) => `/employees/${employeeId}/deactivate`,
    RESIGN: (employeeId) => `/employees/${employeeId}/resign`,
    TERMINATE: (employeeId) => `/employees/${employeeId}/terminate`,
    REACTIVATE: (employeeId) => `/employees/${employeeId}/reactivate`,
    APPROVE: (employeeId) => `/employees/${employeeId}/approve`,
    REJECT: (employeeId) => `/employees/${employeeId}/reject`,
    PROMOTE: (employeeId) => `/employees/${employeeId}/promote`,
    PROMOTION_REQUEST: (employeeId) => `/employees/${employeeId}/promotion-request`,
    TRANSFER: (employeeId) => `/employees/${employeeId}/transfer`,
    TRANSFERS: (employeeId) => `/employees/${employeeId}/transfers`,
  },
  EMPLOYEE_ACTION_REQUESTS: {
    BASE: "/employee-action-requests",
    APPROVE: (requestId) => `/employee-action-requests/${requestId}/approve`,
    REJECT: (requestId) => `/employee-action-requests/${requestId}/reject`,
  },
  CATEGORIES: {
    BASE: "/categories",
    DETAIL: (categoryId) => `/categories/${categoryId}`,
    STATUS: (categoryId) => `/categories/${categoryId}/status`,
  },
  PRODUCTS: {
    BASE: "/products",
    SUMMARY: "/products/summary",
    DETAIL: (productId) => `/products/${productId}`,
    STATUS: (productId) => `/products/${productId}/status`,
  },
  INVENTORY: {
    BASE: "/inventory",
    TRANSACTIONS: "/inventory/transactions",
    LOW_STOCK: "/inventory/low-stock",
    OUT_OF_STOCK: "/inventory/out-of-stock",
    SUMMARY: "/inventory/summary",
    MOVEMENTS_REPORT: "/inventory/reports/movements",
    VALUATION_REPORT: "/inventory/reports/valuation",
    DETAIL: (productId) => `/inventory/${productId}`,
    PRODUCT_TRANSACTIONS: (productId) => `/inventory/${productId}/transactions`,
    STOCK_IN: (productId) => `/inventory/${productId}/stock-in`,
    STOCK_OUT: (productId) => `/inventory/${productId}/stock-out`,
    ADJUST: (productId) => `/inventory/${productId}/adjust`,
    DAMAGED: (productId) => `/inventory/${productId}/damaged`,
    OPENING_STOCK: (productId) => `/inventory/${productId}/opening-stock`,
  },
  LEADS: {
    BASE: "/leads",
    SUMMARY: "/leads/summary",
    UNASSIGNED: "/leads/unassigned",
    FOLLOW_UPS_TODAY: "/leads/follow-ups/today",
    FOLLOW_UPS_OVERDUE: "/leads/follow-ups/overdue",
    FOLLOW_UPS_UPCOMING: "/leads/follow-ups/upcoming",
    ANALYTICS_FUNNEL: "/leads/analytics/funnel",
    ANALYTICS_SOURCES: "/leads/analytics/sources",
    ANALYTICS_PRODUCTS: "/leads/analytics/products",
    ANALYTICS_EMPLOYEES: "/leads/analytics/employees",
    DETAIL: (leadId) => `/leads/${leadId}`,
    MANAGER: (leadId) => `/leads/${leadId}/manager`,
    EMPLOYEE: (leadId) => `/leads/${leadId}/employee`,
    STATUS: (leadId) => `/leads/${leadId}/status`,
    REOPEN: (leadId) => `/leads/${leadId}/reopen`,
    PRIORITY: (leadId) => `/leads/${leadId}/priority`,
    ACTIVITIES: (leadId) => `/leads/${leadId}/activities`,
    FOLLOW_UPS: (leadId) => `/leads/${leadId}/follow-ups`,
    COMPLETE_FOLLOW_UP: (leadId) => `/leads/${leadId}/follow-ups/complete`,
    QUOTATIONS: (leadId) => `/leads/${leadId}/quotations`,
  },
  QUOTATIONS: {
    BASE: "/quotations",
    DETAIL: (quotationId) => `/quotations/${quotationId}`,
    PRINT: (quotationId) => `/quotations/${quotationId}/print`,
    SEND: (quotationId) => `/quotations/${quotationId}/send`,
    ACCEPT: (quotationId) => `/quotations/${quotationId}/accept`,
    REJECT: (quotationId) => `/quotations/${quotationId}/reject`,
    CANCEL: (quotationId) => `/quotations/${quotationId}/cancel`,
    REVISE: (quotationId) => `/quotations/${quotationId}/revise`,
  },
  REGIONS: {
    BASE: "/regions",
    DETAIL: (regionId) => `/regions/${regionId}`,
  },
  DISTRICTS: {
    BASE: "/districts",
    DETAIL: (districtId) => `/districts/${districtId}`,
    ASSIGN: (districtId) => `/districts/${districtId}/assign`,
    REASSIGN: (districtId) => `/districts/${districtId}/reassign`,
    ASSIGN_REVIEW: (districtId) => `/districts/${districtId}/assign/review`,
    ASSIGN_FINALIZE: (districtId) => `/districts/${districtId}/assign/finalize`,
  },
  PUBLIC: {
    CATEGORIES: "/public/categories",
    PRODUCTS: "/public/products",
    PRODUCT_DETAIL: (slug) => `/public/products/${slug}`,
    ENQUIRIES: "/public/enquiries",
  },
});
